### PR TITLE
Allow for more than one autocomplete field.

### PR DESCRIPTION
**Pull request by havocbane**
- Use a form prefix to make name and ID unique.
- Version bump to 0.1.5 (0.1.4 was static files change for Django 3.0)

### CODE REVIEW

**Comment by vigo** [comment]
Hi @havocbane , I did not understand, "more than one autocomplete field" situation? It's already more than one field?

`autocomplete_list_filter = ('category', 'author', 'tags')`

You have 3 different fields and widgets... Can you explain more if possible?

**Comment by havocbane** [comment]
@vigo thank you for your feedback; let me elaborate.

We were seeing an issue where multiple fields would render with default Django form drop-downs instead of auto-complete (the last one in the list filter would always be an auto-complete).

We were able to address this by adding the form prefix when instantiating the autocomplete form so that the elements would have unique names/IDs in the HTML.

**Comment by vigo** [comment]
@havocbane with all due respect, can you please share code snippet? I'd like to produce this issue locally and try to understand better.

**Comment by havocbane** [comment]
> 
> 
> @havocbane with all due respect, can you please share code snippet? I'd like to produce this issue locally and try to understand better.

Sure, I will try to get you a simple example to reproduce the issue next week.

**Comment by vigo** [comment]
Thanks @havocbane , I've picked JavaScript changes manually, others were fixed via @guglielmo 's PR...

**Pull request closed without merging**
